name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  fix-notebooks:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@main
      with:
        ref: main
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@main
      with:
        python-version: '3.10'

    - id: fixNotebooks
      name: Fix notebook output
      uses: GabrielBB/xvfb-action@v1
      with:
        working-directory: ${{ github.workspace }}
        run: |
          python -c "from biosimulator_processes.utils import fix_notebooks_execution_count; fix_notebooks_execution_count(); exit();"
